# sevsev9/simplistic-tsp-implementation
FROM nginx:stable
WORKDIR /usr/share/nginx/html
COPY index.html ./
COPY style.css ./
COPY favicon.ico ./
COPY js/*  ./js/

# docker run -d -p 8080:80 --name web sevsev9/simplistic-tsp-implementation